import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CalendarDays, Clock3, Globe2, Mail, Phone, ShieldAlert, Stethoscope, UserRound } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { AdminWorkspaceHeader } from "../components/AdminWorkspaceHeader";
import { AdminUserLink } from "../components/AdminUserLink";
import { getAdminUser, type AdminUserDetail } from "../api/admin.api";

const statusClass: Record<string, string> = { completed: "bg-emerald-100 text-emerald-700", confirmed: "bg-blue-100 text-blue-700", in_progress: "bg-violet-100 text-violet-700", cancelled: "bg-rose-100 text-rose-700", refunded: "bg-amber-100 text-amber-800", pending_payment: "bg-slate-100 text-slate-700" };

export function AdminUserDetailPage() {
  const { id = "" } = useParams();
  const [user, setUser] = useState<AdminUserDetail | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => { void getAdminUser(id).then(setUser).catch(() => setError(true)); }, [id]);
  if (error) return <DashboardLayout><div className="grid min-h-[60vh] place-items-center"><Card><CardContent className="p-8 text-center"><ShieldAlert className="mx-auto size-10 text-rose-600" /><h1 className="mt-3 font-black">User unavailable</h1><Button asChild className="mt-5"><Link to="/admin/users">Return to directory</Link></Button></CardContent></Card></div></DashboardLayout>;
  if (!user) return <DashboardLayout><div className="grid min-h-[60vh] place-items-center"><Clock3 className="size-8 animate-spin text-primary" /></div></DashboardLayout>;
  return <DashboardLayout><div className="space-y-6"><AdminWorkspaceHeader icon={UserRound} eyebrow={`${user.role} profile`} title={user.name} description="A connected operational view of this account, its care activity, and its relevant professional information." actions={<Button asChild className="h-11 rounded-xl bg-white text-primary hover:bg-violet-50"><Link to="/admin/users"><ArrowLeft className="mr-2 size-4" />All users</Link></Button>} />
    <section className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><Card className="border-slate-100 shadow-sm"><CardContent className="p-6"><div className="flex items-center gap-4"><Avatar className="size-16"><AvatarImage src={user.avatarUrl} alt="" /><AvatarFallback className="bg-violet-100 text-xl font-black text-primary">{user.name.charAt(0)}</AvatarFallback></Avatar><div><h2 className="text-xl font-black text-slate-950">{user.name}</h2><div className="mt-2 flex flex-wrap gap-2"><Badge className="bg-violet-100 text-violet-700">{user.role}</Badge><Badge className={user.isActive ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"}>{user.isActive ? "active" : "suspended"}</Badge></div></div></div><div className="mt-6 grid gap-4 border-t border-slate-100 pt-5 text-sm"><p className="flex items-center gap-3 text-slate-600"><Mail className="size-4 text-primary" />{user.email ?? "No email"}</p><p className="flex items-center gap-3 text-slate-600"><Phone className="size-4 text-primary" />{user.phone ?? "No phone"}</p><p className="flex items-center gap-3 text-slate-600"><Globe2 className="size-4 text-primary" />{user.country} · {user.timezone}</p><p className="text-xs text-slate-400">Joined {new Date(user.createdAt).toLocaleDateString()}</p></div></CardContent></Card><Card className="border-slate-100 shadow-sm"><CardContent className="p-6"><h2 className="font-black text-slate-950">Care activity</h2><div className="mt-5 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-violet-50 p-4"><p className="text-2xl font-black text-violet-950">{user.appointments.length}</p><p className="text-xs font-bold text-slate-500">Recent appointments shown</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-2xl font-black text-emerald-800">{user.appointments.filter((item) => item.status === "completed").length}</p><p className="text-xs font-bold text-slate-500">Completed in this list</p></div></div>{user.psychologist && <div className="mt-5 border-t border-slate-100 pt-5"><h3 className="flex items-center gap-2 font-black text-slate-900"><Stethoscope className="size-4 text-primary" />Professional status</h3><p className="mt-2 text-sm text-slate-600">{user.psychologist.specialization.join(", ") || "No specializations"} · {user.psychologist.experienceYears} years</p><p className="mt-1 text-sm text-slate-600">Onboarding: {user.psychologist.onboardingStatus.replaceAll("_", " ")} · Verification: {user.psychologist.verificationStatus}</p></div>}</CardContent></Card></section>
    <Card className="overflow-hidden border-slate-100 shadow-sm"><CardContent className="p-0"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-black text-slate-950">Recent appointments</h2><p className="mt-1 text-sm text-slate-500">Sensitive concern notes are intentionally not shown in this operational view.</p></div><div className="divide-y divide-slate-100">{user.appointments.map((item) => { const counterpart = user.role === "patient" ? item.psychologist : item.patient; return <div key={item.id} className="flex flex-col gap-3 px-6 py-4 sm:flex-row sm:items-center"><CalendarDays className="size-4 text-primary" /><div className="min-w-0 flex-1"><AdminUserLink {...counterpart} /><p className="mt-1 text-xs text-slate-500">{new Date(item.scheduledAt).toLocaleString()} · {item.mode}</p></div><Badge className={statusClass[item.status] ?? "bg-slate-100 text-slate-700"}>{item.status.replaceAll("_", " ")}</Badge></div>; })}{user.appointments.length === 0 && <p className="px-6 py-12 text-center text-sm text-slate-500">No appointments are recorded for this user.</p>}</div></CardContent></Card>
  </div></DashboardLayout>;
}
