import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, LoaderCircle, Search, ShieldAlert, Stethoscope, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { AdminMetricCard, AdminWorkspaceHeader } from "../components/AdminWorkspaceHeader";
import { AdminUserLink } from "../components/AdminUserLink";
import { getAdminUsers, updateAdminUserActivity, type AdminUserItem } from "../api/admin.api";

export function AdminUsersPage() {
  const [items, setItems] = useState<AdminUserItem[]>([]);
  const [role, setRole] = useState<"all" | "patient" | "psychologist">("all");
  const [status, setStatus] = useState<"all" | "active" | "inactive">("active");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<AdminUserItem | null>(null);
  const [reason, setReason] = useState("");
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); const result = await getAdminUsers({ page: 1, limit: 100, ...(role !== "all" ? { role } : {}), ...(status !== "all" ? { status } : {}), ...(search.trim() ? { search: search.trim() } : {}) }); setItems(result.items); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load users."); } finally { setLoading(false); } }, [role, search, status]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [load]);
  const summary = useMemo(() => ({ patients: items.filter((item) => item.role === "patient").length, psychologists: items.filter((item) => item.role === "psychologist").length, review: items.filter((item) => item.psychologist?.onboardingStatus === "under_review").length, inactive: items.filter((item) => !item.isActive).length }), [items]);
  const changeActivity = async () => { if (!selected || reason.trim().length < 10) return; try { setSaving(true); await updateAdminUserActivity(selected.id, { isActive: !selected.isActive, reason: reason.trim() }); toast.success(`${selected.name}'s account is now ${selected.isActive ? "suspended" : "active"}.`); setSelected(null); setReason(""); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update account status."); } finally { setSaving(false); } };
  return <DashboardLayout><div className="space-y-6"><AdminWorkspaceHeader icon={UsersRound} eyebrow="User management" title="People directory" description="Find patients and psychologists quickly, understand their platform status, and take audited account-safety action when required." />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><AdminMetricCard icon={UsersRound} label="Patients" value={summary.patients} note="Current filtered directory" tone="bg-blue-100 text-blue-700" /><AdminMetricCard icon={Stethoscope} label="Psychologists" value={summary.psychologists} note="Current filtered directory" tone="bg-violet-100 text-violet-700" /><AdminMetricCard icon={ShieldAlert} label="In review" value={summary.review} note="Psychologist onboarding" tone="bg-amber-100 text-amber-800" /><AdminMetricCard icon={Activity} label="Inactive" value={summary.inactive} note="Suspended accounts" tone="bg-rose-100 text-rose-700" /></section>
    <Card className="border-slate-100 shadow-sm"><CardContent className="flex flex-col gap-3 p-4 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="h-11 rounded-xl pl-9" placeholder="Search name, email, or phone" /></div><select value={role} onChange={(event) => setRole(event.target.value as typeof role)} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"><option value="all">All roles</option><option value="patient">Patients</option><option value="psychologist">Psychologists</option></select><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"><option value="all">All account states</option><option value="active">Active</option><option value="inactive">Inactive</option></select></CardContent></Card>
    <Card className="overflow-hidden border-slate-100 shadow-sm"><CardContent className="p-0"><div className="border-b border-slate-100 px-6 py-5"><h2 className="font-black text-slate-950">Directory</h2><p className="mt-1 text-sm text-slate-500">Suspending an account invalidates existing sessions. Every status change needs a reason and is audit-logged.</p></div>{loading ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="size-8 animate-spin text-primary" /></div> : <div className="divide-y divide-slate-100">{items.map((item) => <article key={item.id} className="flex flex-col gap-4 px-6 py-5 transition-colors hover:bg-violet-50/30 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><AdminUserLink id={item.id} name={item.name} avatarUrl={item.avatarUrl} /><Badge className={item.role === "psychologist" ? "bg-violet-100 text-violet-700" : "bg-blue-100 text-blue-700"}>{item.role}</Badge><Badge className={item.isActive ? "bg-emerald-100 text-emerald-700" : "bg-rose-100 text-rose-700"}>{item.isActive ? "active" : "suspended"}</Badge>{!item.isVerified && <Badge className="bg-amber-100 text-amber-800">unverified</Badge>}</div><p className="mt-1 truncate text-sm text-slate-500">{item.email ?? item.phone ?? "No contact detail"} · {item.country}</p>{item.psychologist && <p className="mt-1 text-xs font-medium text-slate-600">Onboarding: {item.psychologist.onboardingStatus.replaceAll("_", " ")} · {item.appointmentCount} appointments</p>}</div><div className="text-sm text-slate-600"><b className="block text-slate-900">{item.appointmentCount}</b><span>appointments</span></div><Button variant={item.isActive ? "outline" : "default"} onClick={() => setSelected(item)} className={item.isActive ? "h-10 rounded-xl border-rose-200 text-rose-700 hover:bg-rose-50" : "h-10 rounded-xl"}>{item.isActive ? "Suspend" : "Reactivate"}</Button></article>)}{items.length === 0 && <p className="px-6 py-14 text-center text-sm text-slate-500">No users match these filters.</p>}</div>}</CardContent></Card>
    <Dialog open={selected !== null} onOpenChange={(open) => !open && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?.isActive ? "Suspend account" : "Reactivate account"}</DialogTitle><DialogDescription>{selected?.isActive ? "This immediately invalidates the user’s existing sessions and blocks access until reactivated." : "This restores the user’s ability to sign in after their next authentication."}</DialogDescription></DialogHeader><label className="grid gap-2 text-sm font-bold">Reason <textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={10} rows={4} placeholder="Record why this action is required." className="resize-none rounded-xl border p-3 font-normal outline-none focus:border-primary" /></label><DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>Cancel</Button><Button onClick={() => void changeActivity()} disabled={saving || reason.trim().length < 10} className={selected?.isActive ? "bg-rose-600 hover:bg-rose-700" : ""}>{saving && <LoaderCircle className="mr-2 size-4 animate-spin" />}{selected?.isActive ? "Suspend account" : "Reactivate account"}</Button></DialogFooter></DialogContent></Dialog>
  </div></DashboardLayout>;
}
